[ERROR]
0001=EMG1 S/W (X0300) 를 해제하여 주십시오.
0002=EMG2 S/W (X0301) 를 해제하여 주십시오.
0003=EMG3 S/W (X0302) 를 해제하여 주십시오.
0004=EMG4 S/W (X0303) 를 해제하여 주십시오.
0005=
0006=
0007=Main Air1 (X0304) 공압상태 확인해 주세요.
0008=
0009=
0011=Main Door1 (X0322) 이 열렸습니다. 확인하여 주십시오.
0012=Main Door2 (X0323) 이 열렸습니다. 확인하여 주십시오.
0013=Main Door3 (X0324) 이 열렸습니다. 확인하여 주십시오.
0014=Main Door4 (x0325) 이 열렸습니다. 확인하여 주십시오.
0015=Main Door5 (x0326) 이 열렸습니다. 확인하여 주십시오.
0016=Main Door6 (x0327) 이 열렸습니다. 확인하여 주십시오.
0017=Main Door7 (x0328) 이 열렸습니다. 확인하여 주십시오.
0018=Main Door8 (x0329) 이 열렸습니다. 확인하여 주십시오.

0040=초기화가 완료되지 않았습니다. 초기화 완료 후 진행하여 주십시오.

0100=MZ Elevator Z 축   서보 OFF 상태입니다. 확인하여 주십시오.
0101=TRAY FEEDER X 축   서보 OFF 상태입니다. 확인하여 주십시오.
0102=TRAY FEEDER Y 축   서보 OFF 상태입니다. 확인하여 주십시오.
0103=TRAY PICKER Y 축   서보 OFF 상태입니다. 확인하여 주십시오.
0104=TRAY PICKER Z 축   서보 OFF 상태입니다. 확인하여 주십시오.
0105=TOP INSPECTOR X 축 서보 OFF 상태입니다. 확인하여 주십시오.
0106=TOP INSPECTOR Y 축 서보 OFF 상태입니다. 확인하여 주십시오.
0107=TOP INSPECTOR Z 축 서보 OFF 상태입니다. 확인하여 주십시오.
0108=BTM INSPECTOR X 축 서보 OFF 상태입니다. 확인하여 주십시오.
0109=BTM INSPECTOR Y 축 서보 OFF 상태입니다. 확인하여 주십시오.
0110=BTM INSPECTOR Z 축 서보 OFF 상태입니다. 확인하여 주십시오.
0111=MARK UNIT R 축     서보 OFF 상태입니다. 확인하여 주십시오.
0112=MARK UNIT X 축     서보 OFF 상태입니다. 확인하여 주십시오.
0113=MARK UNIT X 축     서보 OFF 상태입니다. 확인하여 주십시오.
0114=MARK UNIT Z 축     서보 OFF 상태입니다. 확인하여 주십시오.
0115=MAIN INDEX R 축    서보 OFF 상태입니다. 확인하여 주십시오.


0200=MZ Elevator Z 축   드라이버 알람 상태 입니다. 확인하여 주십시오.
0201=TRAY FEEDER X 축   드라이버 알람 상태 입니다. 확인하여 주십시오.
0202=TRAY FEEDER Y 축   드라이버 알람 상태 입니다. 확인하여 주십시오.
0203=TRAY PICKER Y 축   드라이버 알람 상태 입니다. 확인하여 주십시오.
0204=TRAY PICKER Z 축   드라이버 알람 상태 입니다. 확인하여 주십시오.
0205=TOP INSPECTOR X 축 드라이버 알람 상태 입니다. 확인하여 주십시오.
0206=TOP INSPECTOR Y 축 드라이버 알람 상태 입니다. 확인하여 주십시오.
0207=TOP INSPECTOR Z 축 드라이버 알람 상태 입니다. 확인하여 주십시오.
0208=BTM INSPECTOR X 축 드라이버 알람 상태 입니다. 확인하여 주십시오.
0209=BTM INSPECTOR Y 축 드라이버 알람 상태 입니다. 확인하여 주십시오.
0210=BTM INSPECTOR Z 축 드라이버 알람 상태 입니다. 확인하여 주십시오.
0211=MARK UNIT R 축     드라이버 알람 상태 입니다. 확인하여 주십시오.
0212=MARK UNIT X 축     드라이버 알람 상태 입니다. 확인하여 주십시오.
0213=MARK UNIT X 축     드라이버 알람 상태 입니다. 확인하여 주십시오.
0214=MARK UNIT Z 축     드라이버 알람 상태 입니다. 확인하여 주십시오.
0215=MAIN INDEX R 축    드라이버 알람 상태 입니다. 확인하여 주십시오.


0300=MZ Elevator Z 축   상한 리미트 센서가 감지 되었습니다. 확인하여 주십시오.
0301=TRAY FEEDER X 축   상한 리미트 센서가 감지 되었습니다. 확인하여 주십시오.
0302=TRAY FEEDER Y 축   상한 리미트 센서가 감지 되었습니다. 확인하여 주십시오.
0303=TRAY PICKER Y 축  
0304=TRAY PICKER Z 축   상한 리미트 센서가 감지 되었습니다. 확인하여 주십시오.
0305=TOP INSPECTOR X 축 상한 리미트 센서가 감지 되었습니다. 확인하여 주십시오.
0306=TOP INSPECTOR Y 축 상한 리미트 센서가 감지 되었습니다. 확인하여 주십시오.
0307=TOP INSPECTOR Z 축 상한 리미트 센서가 감지 되었습니다. 확인하여 주십시오.
0308=BTM INSPECTOR X 축 상한 리미트 센서가 감지 되었습니다. 확인하여 주십시오.
0309=BTM INSPECTOR Y 축 상한 리미트 센서가 감지 되었습니다. 확인하여 주십시오.
0310=BTM INSPECTOR Z 축 상한 리미트 센서가 감지 되었습니다. 확인하여 주십시오.
0311=MARK UNIT R 축     상한 리미트 센서가 감지 되었습니다. 확인하여 주십시오.
0312=MARK UNIT X 축     상한 리미트 센서가 감지 되었습니다. 확인하여 주십시오.
0313=MARK UNIT X 축     상한 리미트 센서가 감지 되었습니다. 확인하여 주십시오.
0314=MARK UNIT Z 축     상한 리미트 센서가 감지 되었습니다. 확인하여 주십시오.
0315=MAIN INDEX R 축    상한 리미트 센서가 감지 되었습니다. 확인하여 주십시오.


0400=MZ Elevator Z 축   하한 리미트 센서가 감지 되었습니다. 확인하여 주십시오.
0401=TRAY FEEDER X 축   하한 리미트 센서가 감지 되었습니다. 확인하여 주십시오.
0402=TRAY FEEDER Y 축   하한 리미트 센서가 감지 되었습니다. 확인하여 주십시오.
0403=TRAY PICKER Y 축   하한 리미트 센서가 감지 되었습니다. 확인하여 주십시오.
0404=TRAY PICKER Z 축   하한 리미트 센서가 감지 되었습니다. 확인하여 주십시오.
0405=TOP INSPECTOR X 축 하한 리미트 센서가 감지 되었습니다. 확인하여 주십시오.
0406=TOP INSPECTOR Y 축 하한 리미트 센서가 감지 되었습니다. 확인하여 주십시오.
0407=TOP INSPECTOR Z 축 하한 리미트 센서가 감지 되었습니다. 확인하여 주십시오.
0408=BTM INSPECTOR X 축 하한 리미트 센서가 감지 되었습니다. 확인하여 주십시오.
0409=BTM INSPECTOR Y 축 하한 리미트 센서가 감지 되었습니다. 확인하여 주십시오.
0410=BTM INSPECTOR Z 축 하한 리미트 센서가 감지 되었습니다. 확인하여 주십시오.
0411=MARK UNIT R 축     하한 리미트 센서가 감지 되었습니다. 확인하여 주십시오.
0412=MARK UNIT X 축     하한 리미트 센서가 감지 되었습니다. 확인하여 주십시오.
0413=MARK UNIT X 축     하한 리미트 센서가 감지 되었습니다. 확인하여 주십시오.
0414=MARK UNIT Z 축     하한 리미트 센서가 감지 되었습니다. 확인하여 주십시오.
0415=MAIN INDEX R 축    하한 리미트 센서가 감지 되었습니다. 확인하여 주십시오.


0500=MZ Elevator Z 축   Home이 완료되지 않았습니다. Home 완료 후 진행하여 주십시오.
0501=TRAY FEEDER X 축   Home이 완료되지 않았습니다. Home 완료 후 진행하여 주십시오.
0502=TRAY FEEDER Y 축   Home이 완료되지 않았습니다. Home 완료 후 진행하여 주십시오.
0503=TRAY PICKER Y 축  
0504=TRAY PICKER Z 축   Home이 완료되지 않았습니다. Home 완료 후 진행하여 주십시오.
0505=TOP INSPECTOR X 축 Home이 완료되지 않았습니다. Home 완료 후 진행하여 주십시오.
0506=TOP INSPECTOR Y 축 Home이 완료되지 않았습니다. Home 완료 후 진행하여 주십시오.
0507=TOP INSPECTOR Z 축 Home이 완료되지 않았습니다. Home 완료 후 진행하여 주십시오.
0508=BTM INSPECTOR X 축 Home이 완료되지 않았습니다. Home 완료 후 진행하여 주십시오.
0509=BTM INSPECTOR Y 축 Home이 완료되지 않았습니다. Home 완료 후 진행하여 주십시오.
0510=BTM INSPECTOR Z 축 Home이 완료되지 않았습니다. Home 완료 후 진행하여 주십시오.
0511=MARK UNIT R 축     Home이 완료되지 않았습니다. Home 완료 후 진행하여 주십시오.
0512=MARK UNIT X 축     Home이 완료되지 않았습니다. Home 완료 후 진행하여 주십시오.
0513=MARK UNIT X 축     Home이 완료되지 않았습니다. Home 완료 후 진행하여 주십시오.
0514=MARK UNIT Z 축     Home이 완료되지 않았습니다. Home 완료 후 진행하여 주십시오.
0515=MAIN INDEX R 축    Home이 완료되지 않았습니다. Home 완료 후 진행하여 주십시오.


; 0. Initial_MainInit (1000)
1002=Elevator 1 or 2에 Magazine이 감지상태 확인 바랍니다. 
1003=Tray Picker에 Tray가 감지상태 확인 바랍니다.
1004=Feeder에 Tray 감지 상태 확인 바랍니다. 
1005=Feeder Rail에 Tray 감지 상태 확인 바랍니다.
1006=Feeder Magazine 센서 감지 상태 확인 바랍니다. 


; 1. Initial_Conveyor (1100)
1102=
1103=
1104=
1105=
1106=
1111=
1112=
1114=
1115=
1116=

; 2. Initial_MZ_Elevator (1200)
1201=Elevator에 Magazine 감시 상태 확인 바랍니다. 
1202=Feeder Y Ready 위치 아닙니다.
1203=Elevator Z축 Home 상태 아닙니다.
1204=이상없으면 다시 스타트 해주세요. Elevator Ready 위치로 이동합니다.
1205=
1212=
1213=
1214=
1215=
1216=
1217=

; 3. Initial_Feeder (1300)
1301=Feeder에 Tray가 감지되면 안됩니다.
1302=Feeder에 Magazine이 감지되면 안됩니다. 
1303=Rail에 Tray가 감지되면 안됩니다. 혹은 트레이 피커 초기화 상태 확인 바랍니다. 
1305=Tray Picker 초기화 상태 확인 바랍니다. 
1306=Feeder Y축 동작중입니다.
1307=Feeder X축 Home 상태 아닙니다. Feeder Y 축 Ready 위치 아닙니다. 

; 4. Initial_TrayPicker (1400)
1401=Picker에 Tray가 감지되면 안됩니다.
1402=이상없으면 Start 바랍니다. Tray Picker Z축 Home 동작 합니다.
1403=Tray Picker Z축 Home 상태 아닙니다. 
1404=이상없으면 Start 바랍니다. Tray Picker Z축 Ready 위치로 이동합니다. 
1410=Tray Picker Z 축 Ready 위치 아닙니다. 
1411=이상없으면 Start 바랍니다. Tray Picker Y축 Home 동작 합니다. 
1412=Tray Picker Y축 Home 상태 아닙니다. 
1413=이상 없으면 Start 바랍니다. Tray Picker Y축 Ready 위치로 이동합니다. 
1414=Tray Picker Y축 Ready 위치 아닙니다. 
1415=이상 없으면 Start 바랍니다. Tray Picker Master&Slave Out 합니다. 
1416=Tray Picker Master&Slave Out 상태 아닙니다. 

; 5. Initial_LensCleaner (1500)
1501=이상없으면 시작하세요. Cleaner Open 합니다.
1502=Cleaner Open 상태 아닙니다. 
1510=Cleaner Backward 상태 아닙니다.


; 6. Initial_TopInspector (1600)
1602=이상 점검 후 시작하세요.Top Insepct Z 축 Home 동작 합니다.
1603=Top Inspect Z축 Home 아닙니다. 
1604=이상 점검 후 시작하세요.Top Inspect Ready 위치로 동작합니다. 
1610=Top Inspect Z축 Ready 위치 아닙니다. 
1611=이상 점검 후 시작하세요.Top Insepct Y축 Home 동작 합니다. 
1612=Top Insepct Y축 Home 상태 아닙니다. 
1613=이상 점검 후 시작하세요. Top Inspect Y축 Ready 위치로 이동합니다.  
1614=Top Insepct Y축 Ready위치 아닙니다.
1615=이상 점검 후 시작하세요.Top Insepct X축 Home 동작 합니다. 
1616=Top Insepct X축 Home 상태 아닙니다. 
1617=Top Insepct X축 Ready위치 아닙니다.

; 7. Initial_BtmInspector (1700)
1602=이상 점검 후 시작하세요.Btm Insepct Z 축 Home 동작 합니다.
1603=Btm Inspect Z축 Home 아닙니다. 
1604=이상 점검 후 시작하세요.Btm Inspect Ready 위치로 동작합니다. 
1610=Btm Inspect Z축 Ready 위치 아닙니다. 
1611=이상 점검 후 시작하세요.Btm Insepct Y축 Home 동작 합니다. 
1612=Btm Insepct Y축 Home 상태 아닙니다. 
1613=이상 점검 후 시작하세요. Btm Inspect Y축 Ready 위치로 이동합니다.  
1614=Btm Insepct Y축 Ready위치 아닙니다.
1615=이상 점검 후 시작하세요.Btm Insepct X축 Home 동작 합니다. 
1616=Btm Insepct X축 Home 상태 아닙니다. 
1617=Btm Insepct X축 Ready위치 아닙니다.

; 8. Initial_MarkUnit (1800)
1602=이상 점검 후 시작하세요. Mark Unit Z 축 Home 동작 합니다.
1603=Mark Unit Z축 Home 아닙니다. 
1604=이상 점검 후 시작하세요.Mark Unit Ready 위치로 동작합니다. 
1610=Mark Unit Z축 Ready 위치 아닙니다. 
1611=이상 점검 후 시작하세요.Mark Unit Y축 Home 동작 합니다. 
1612=Mark Unit Y축 Home 상태 아닙니다. 
1613=이상 점검 후 시작하세요. Mark Unit Y축 Ready 위치로 이동합니다.  
1614=Mark Unit Y축 Ready위치 아닙니다.
1615=이상 점검 후 시작하세요.Mark Unit X축 Home 동작 합니다. 
1616=Mark Unit X축 Home 상태 아닙니다. 
1617=Mark Unit X축 Ready위치 아닙니다.

; 9. Initial_MainIndex (1900)
1902=이상 점검 후 시작하세요. 인덱스 Index Align Out 합니다.
1903=Index Align Out 아닙니다.
1904=Tray Picker, Top, Btm, Mark Z축 Ready 위치 아닙니다. Cleaner Open 아닙니다.
1905=Index R축 Home 상태 아닙니다.


; Main Sequence
; 1. TrayPicker_Run (3100)
3102=#1.Tray Picker Z축이 Ready Up 상태인지 확인하여 주십시오.#2.Tray Picker R축이 Ready 상태인지 확인하여 주십시오.
3103=#1.Tray Picker X축이 AVI 위치인지 확인하여 주십시오.#2.Tray Picker R축이 Ready 위치인지 확인하여 주십시오.
3106=#1.Tray Picker Grip이 Open 상태인지 확인하여 주십시오.#2.Tray Picker X축이 AVI 위치인지 확인하여 주십시오.#3.Tray Pickr R축이 Ready 상태인지 확인하여 주십시오.
3107=Tray Picker Z축이 AVI Down 위치인지 확인하여 주십시오.
3108=#1.Tray Picker Grip Close 상태인지 확인하여 주십시오.#2.Tray가 감지되었는지 확인하여 주십시오.
3109=#1.Tray Picker Z축이 Ready Up 위치인지 확인하여 주십시오.#2.Tray가 감지되었는지 확인하여 주십시오.
3111=#1.Tray Picker Z축이 Ready Up 위치인지 확인하여 주십시오.#2.Tray가 감지되었는지 확인하여 주십시오.
3112=#1.Tray Picker X축이 Tray Rotate 위치인지 확인하여 주십시오.#2.Tray Picker Z축이 Ready Up 위치인지 확인하여 주십시오.
3113=#1.Tray Picker R축이 Rotate 위치인지 확인하여 주십시오.#2.Tray Picker Z축이 Ready Up 위치인지 확인하여 주십시오.
3114=#1.Tray Picker R축이 Ready 위치인지 확인하여 주십시오.#2.Tray Picker Z축이 Ready Up 위치인지 확인하여 주십시오.
3120=Tray Picker X축이 Load Port1 위치인지 확인하여 주십시오.
3122=#1.Tray Picker X축이 Load Port1 위치인지 확인하여 주십시오.#2.Tray Picker R축 위치를 확인하여 주십시오.
3123=Tray Picker Z축이 Load Port Down 위치인지 확인하여 주십시오.
3124=Tray Picker Grip이 open 상태인지 확인하여 주십시오.
3125=#1.Tray Picker Z축이 Ready Up 위치인지 확인하여 주십시오.#2.Tray가 감지되고 있습니다. Tray 확인 센서를 확인하여 주십시오.
3126=Tray Picker X축이 Tray Rotate 위치인지 확인하여 주십시오.
3127=Tray Picker R축이 Ready 위치인지 확인하여 주십시오.
3130=#1.Tray Picker X축이 AVI 위치인지 확인하여 주십시오.#2.Tray Picker R축 위치를 확인하여 주십시오.
3150=#1.Tray Picker Z축이 Ready Up 상태인지 확인하여 주십시오.#2.Tray Picker R축이 Ready 상태인지 확인하여 주십시오.
3151=#1.Tray Picker X축이 Tray Rotate 위치인지 확인하여 주십시오.#2.Tray Picker Grip이 Open 상태인지 확인하여 주십시오.

; 2. MZElevRun (3400)
3401=#1.Load Stoppper Down 아닙니다.#2.Elevator Z축 Load 위치 아닙니다. 
3403=#1.Elevator Exist1 (Left) 센서 인식 안됩니다. 
3404=#1.Elevator Exist2 (Right) 센서 인식 안됩니다. 
3405=#1.Elevator Lift 2 Down or Out 아닙니다. 
3406=#1.Elevator Lift 2 Up or Out 아닙니다.
3407=#1.Elevator Lift 2 In or Up 아닙니다. 
3408=#1.Vision Lot Ready 확인바랍니다. Retry 가능합니다. 

3411=#1.Elevator Exist1 인식 안됩니다.
3412=#1.Elevator Lift 1 Out or Down 아닙니다.
3414=#1.Elevator Lift 1 Out or Up 아닙니다.
3415=#1.Elevator Lift 1 In or Up 아닙니다.
3416=#1.Vision Lot Ready 확인바랍니다. Retry 가능합니다. 

3434=#1.Elevator Exist2 인식 안됩니다. #2.Elevator Lift 2 Up or In 아닙니다. 
3436=#1.Elevator Lift 2 Down 아닙니다. 
3438=#1.Elevator Lift 2 Out 아닙니다.
3439=#1.Elevator Unload Conveyor Exist 1 인식 안됩니다.

3453=#1.Elevator Lift 1 Out 아닙니다.
3455=#1.Elevator Lift 1 or 2 Down 아닙니다. #2. Elevator Lift 1 or 2 Out 아닙니다. 
3460=#1.Elevator Lift 2 Up 아닙니다.
3461=#1.Elevator Lift 2 In 아닙니다.


; 3. FeederRun (3700)
3702=#1.Feeder Y축 Ready or Load 위치 아닙니다.
3703=#1.Elevator Z 이동 위치 확인바랍니다. #2. Feeder X축 Load 위치 아닙니다. 
3704=#1.Feeder Y축 Load 위치 아닙니다. 
3710=#1.Feeder Y축 Load 위치 아닙니다.
3711=#1.Feeder Grip Close 아닙니다. 
3712=#1.Feeder Y축 Coating Zig Grip 위치 아닙니다.
3713=#1.Feeder X축 Coating Zig Grip 위치 아닙니다.
3714=#1.Feeder X축 Coating Zig Grip 위치 아닙니다.

3715=#1.Feeder Y축 Ready 위치 아닙니다.#2. Rail 위치 Zig 인식 안됩니다.
3716=#1.Rail Aligner In 아닙니다.
3717=#1.Rail Aligner Out 아닙니다. 
3731=#1.Feeder Y축 Ready 위치 아닙니다. #2.Feeder X축 Coating Zig grip 위치 아닙니다. #3.Feeder Open 아닙니다. 
3732=#1.Feeder Y축 Coating Zig grip 위치 아닙니다. #2.Feeder Open 아닙니다. 
3734=#1.Feeder Close 인식 안됩니다.
3736=#1.Feeder X축 Load 위치 아닙니다.
3737=#1.Feeder Y축 Load 위치 아닙니다. 
3738=#1.Feeder Open 아닙니다.
3740=#1.Feeder Y축 Ready 위치 아닙니다.

3752=#1.Feeder Y축 Ready 위치 아닙니다.#2.Feeder Y축 MZ(Rdy) 위치 아닙니다
3753=#1.Elevator Z축 위치 확인 바랍니다.#2.Feeder X축 MZ(Rdy) 위치 아닙니다. 
3754=#1.Feeder Y축 MZ(Rdy)위치 아닙니다.
3760=#1.Feeder Y축 MZ(Rdy)위치 아닙니다.
3761=#1.Feeder Grip Close 인식 안됩니다. 
3762=#1.Feeder Y축 Zig Grip 위치 아닙니다.
3763=#1.Feeder X축 Zig Grip 위치 아닙니다.
3764=#1.Feeder Grip Open 인식 안됩니다.
3765=#1.Feeder Y축 Ready 위치 아닙니다.


; 4. ZigPickerRun (4000)
4002=Picker Y축 Load 위치 아닙니다.
4003=Picker Z축 Load Down 아닙니다.
4004=Picker Master In 아닙니다.
4005=#1.Picker Master and Slave In 아닙니다. #2.Picker Zig 유무 인식 안됩니다.
4011=#1.Picker Z축 Ready 위치 아닙니다. #2. Rail 위치 Zig 유무 인식 안됩니다.
4012=#1.Picker Y Index 위치 아닙니다. #2. Index Load Align Out 아닙니다.
4013=#1.Picker Z축 Index Down 위치 아닙니다.
4014=#1.Picker Slave Out 아닙니다.
4015=#1.Picker Master Slave Out 아닙니다.
4016=#1.Picker Z축 Ready 위치 아닙니다. #2.Picker Zig 유무 인식 되면 안됩니다.

4021=#1.Picker Z축 Ready 위치 아닙니다. #2.Picker Zig 유무 인식 되면 안됩니다. 
4022=#1.Picker Y축 Index 위치 아닙니다. #2.Index Load Align Out 아닙니다. 
4023=#1.Picker Z축 Index Unload 위치 아닙니다.
4024=#1.Picker Master In 아닙니다.
4025=#1.Picker Master Slave In 아닙니다.
4026=#1.Picker Z축 Ready 위치 아닙니다.#2.Picker Zig 유무 인식 안됩니다.
4027=#1.Picker Y축 Load 위치 아닙니다.#2.Feeder X Zig Grip 위치 아닙니다.#3.Feeder Y축 Ready위치 아닙니다.
4028=#1.Picker Z축 Load Down 위치 아닙니다. 
4029=#1.Picker Slave Out 아닙니다.
4030=#1.Picker Master Slave Out 아닙니다. #2.Index포켓 Zig 유무 인식 안됩니다.
4031=#1.Picker Z축 Ready 위치 아닙니다.#2.Picker Zig 유무 인식 되면 안됩니다.




; 5. LensCleanerRun (3500)
4301=
4303=
4304=
4305=
4306=


; 6. TopInspectorRun (4600)
4601=
4603=
4604=
4605=
4606=


; 7. BtmInspectorRun (4900)
4901=
4902=
4905=
4906=
4910=
4915=
4916=
4917=

; 8. MarkUnitRun (5200)
5201=
5202=
5205=
5206=
5210=
5215=
5216=
5217=



; 9. MainIndexRun (5500)


; 10. UnloadConveyorRun (5800)


; Inspector
6100=검사 Vision에서 찍힘이 연속 발생하였습니다. 확인하여 주십시오.
6101=Vision Inspector 프로그램의 TrayNo와 CmNo 값에 오류가 있습니다. 로그를 확인해 주십시요.
6102=Vision Inspector 프로그램의 구분자가 정확하지 않습니다. 로그를 확인해 주십시요.
6103=Vision 검사 결과 Tray번호 CM번호가 일치하지 않습니다.
6104=Vision 검사 결과 동일한 위치에서 불량이 연속 발생하였습니다. 확인하여 주십시오.
6110=비전 하드디스크 용량이 초과되었습니다. 불필요한 이미지 파일 삭제 후 진행하여 주십시오.
6111=Vision HDD 상태에 대한 응답이 없습니다. Vision PC와 연결상태를 확인하십시오.
6120=Module 안착상태 이상으로 Top1 Mirror Z축을 내릴 수 없습니다.
6130=BTM2 Picker 모듈상태 확인 후 모듈을 정렬해 주십시오.
6131=Angle Port에 있는 Tray 안의 모듈 상태를 확인 하여 주십시오.
6141=Vision PC 1 의 프로그램 버전 또는 파라메터 버전을 확인하여 주십시오.
6142=Vision PC 2 의 프로그램 버전 또는 파라메터 버전을 확인하여 주십시오.
6143=Vision PC 3 의 프로그램 버전 또는 파라메터 버전을 확인하여 주십시오.
6144=Vision PC 4 의 프로그램 버전 또는 파라메터 버전을 확인하여 주십시오.

; Aligner
6201=Vision Aligner 프로그램의 MainNo와 SubNo 값에 오류가 있습니다. 로그를 확인해 주십시요.
6202=Vision Aligner 프로그램의 구분자가 정확하지 않습니다. 로그를 확인해 주십시요.
6210=Align Load 1 NG입니다. 확인해 주십시요.
6211=Align Load 2 NG입니다. 확인해 주십시요.
6212=Align Module 1 NG입니다. 확인해 주십시요.
6213=Align Module 2 NG입니다. 확인해 주십시요.
6214=Align Cap 1 NG입니다. 확인해 주십시요.
6215=Align Cap 2 NG입니다. 확인해 주십시요.
6220=Cap Direction NG 입니다. 확인해 주십시요.

; MES
9001=MES에서 Lot Start에 대한 응답이 없습니다(TimeOver). MES 확인 후 진행하여 주시기 바랍니다.
9002=MES에서 Lot Start를 취소하였습니다. MES 확인 후 진행하여 주시기 바랍니다.
9003=MES Lot ID가 다름니다. MES 확인 후 진행하여 주시기 바랍니다.
9004=MES Lot 수량이 다름니다. MES 확인 후 진행하여 주시기 바랍니다.

9011=MES에서 Cap ID 전송에 대한 응답이 없습니다(TimeOver). MES 확인 후 진행하여 주시기 바랍니다.
9012=MES에서 Cap ID 전송을 취소하였습니다. MES 확인 후 진행하여 주시기 바랍니다.

9021=MES에서 Ship ID 전송에 대한 응답이 없습니다(TimeOver). MES 확인 후 진행하여 주시기 바랍니다.
9022=MES에서 Ship ID 전송을 취소하였습니다. MES 확인 후 진행하여 주시기 바랍니다.
